export default {
    ior: [
        '/assets/example1.jpg',
        '/assets/example2.jpg',
        '/assets/example3.jpg',
        '/assets/example1.jpg',
        '/assets/example2.jpg',
        '/assets/example3.jpg',
        '/assets/example1.jpg',
        '/assets/example2.jpg',
        '/assets/example3.jpg',
        '/assets/example1.jpg',
        '/assets/example2.jpg',
        '/assets/example3.jpg',
    ],
    icml: [
        '/assets/example1.jpg',
        '/assets/example2.jpg',
        '/assets/example3.jpg',
        '/assets/example1.jpg',
        '/assets/example2.jpg',
        '/assets/example3.jpg',
        '/assets/example1.jpg',
    ],
    ielsg: [
        '/assets/example1.jpg',
        '/assets/example2.jpg',
        '/assets/example3.jpg',
        '/assets/example1.jpg',
        '/assets/example2.jpg',
        '/assets/example3.jpg',
        '/assets/example1.jpg',
    ],
};