backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

public_folder: "/uploads" # Folder path where uploaded files will be accessed, relative to the base of the built site
media_library:
  name: uploadcare
  config:
    publicKey: 2777696613d6e0f27af8

collections:
  - name: "council" # Used in routes, e.g., /admin/collections/coucil
    label: "Member" # Used in the UI
    folder: "src/data/members" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{name-and-surname}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter. 
      - {label: "Layout", name: "layout", widget: "hidden", default: "council"}
      - {label: "[EN] Name and Surname", name: "name-and-surname", widget: "string"}
      - {label: "[EN] Title", name: "title", widget: "select", options: ['Prof.', 'Mr.', 'Phd.', 'Doc.']}
      - {label: "[EN] Role", name: "role", widget: "string"}
      - {label: "[EN] Bio", name: "bio", widget: "text"}
      - {label: "[IT] Titolo", name: "title-it", widget: "select", options: ['Prof.', 'Sign.', 'Dott.']}
      - {label: "[EN] Ruolo", name: "role-it", widget: "string"}
      - {label: "[IT] Biografia", name: "bio-it", widget: "text"}
      - {label: "E-mail", name: "email", widget: "string", pattern: [`[a-z0-9!#$%&'*+/=?^_`{|}~-]+(?:\.[a-z0-9!#$%&'*+/=?^_`{|}~-]+)*@(?:[a-z0-9](?:[a-z0-9-]*[a-z0-9])?\.)+[a-z0-9](?:[a-z0-9-]*[a-z0-9])?`, "Please insert a valid email"]}
      - {label: "Board of directors", name: "board-of-directors", widget: "boolean"}
      - {label: "Not member anymore", name: "not-anymore", widget: "boolean"}
      - {label: "Portrait Picture", name: "picture", widget: "image"}
